### PR TITLE
Add support for logging lottery winnings to a MySQL database

### PR DESCRIPTION
**Pull request by goosewoman**
Adds support for logging lottery winnings to a MySQL database

### CODE REVIEW

**Comment by goosewoman** [comment]
https://gist.github.com/kukelekuuk00/6107913  the sql queries for creating database and table

**Comment by khobbits** [comment]
This runs mysql queries in thread, meaning it locks the server up while the query is running, this will not be added in it's current form.

**Comment by goosewoman** [comment]
https://gist.github.com/kukelekuuk00/4c5410b33130c2311d76

Would something like that work?

**Comment by khobbits** [comment]
Close but it should be using this to fire the task:

http://jd.bukkit.org/beta/apidocs/src-html/org/bukkit/scheduler/BukkitScheduler.html#line.177

**Comment by goosewoman** [comment]
I stopped lottery from canceling tasks because it kept canceling the addWinToDBTask while it was in queue, the only difference this should make is that the lottery timer will act a bit more sporadic when the addWinToDBTask is being done, in the end the difference isn't noticable, because of the way the lottery timer works.

**Pull request closed without merging**
